# Данные для доступа к базе данных
db_access:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: home!db_228
  db_name: postgres
  table_name: test

# Осуществлять полный сбор объявлений
deep_scan: !!bool True

# Сбор объявлений за n дней
look_up_date: !!int 2

use_multiprocessing: !!bool True
num_process: !!int 5

# Режим работы сбора ссылок и данных с объявлений
# get_ads - собирать ссылки объявлений
# ads_data - собирать информацию из объявлений
# all - Выполнить полный сбор данных. Очередность сбора 1 - сбор ссылок, 2 - сбор информации
work_mode: !!str all

# Задержка между загрузкой страниц в секундах
delay: 
  from: !!int 10
  to: !!int 10

# Использовать прокси при сборе
use_proxy: !!bool True

# Сохранять объявления которые проверялись
save_checked_ads: !!bool True

# Осуществлять проверку объявлений с теми которые ранее уже собирались
check_new_ad_on_processed: !!bool True
