# Московская область: 1
# Москва: 2
# Москва и МО: 3
# Калужская область: 4
# Калуга: 5
# Обнинск: 6
location: 1

# Купить жильё/Все квартиры: 1
# Купить жильё/Вторичка: 2
# Купить жильё/Новостройки: 3
# Купить жильё/Дома, дачи и коттеджи: 4
# Купить жильё/Комнаты: 5

# Снять посуточно/Квартиры: 6
# Снять посуточно/Дома, дачи и коттеджи: 7
# Снять посуточно/Комнаты и койко-места: 8

# Снять долгосрочно/Квартиры: 9
# Снять долгосрочно/Дома, дачи и коттеджи: 10
# Снять долгосрочно/Комнаты и койко-места: 11

# Коммерческая недвижимость/Купить: 12
# Коммерческая недвижимость/Снять: 13

# Другие категории/Земельные участки: 14
# Другие категории/Гаражи и машиноместа: 15
# Другие категории/Зарубежная недвижимость: 16
category: 1      

# Осуществлять полный сбор объявлений
deep_scan: !!bool True

# Сбор объявлений за n дней
look_up_date: !!int 2

# Формат сохраняемого файла
# json - сохранять данные в формате json
# excel - сохранять данные в формате excel
result_format: !!str excel

# Сохранять объявления которые проверялись
save_checked_ads: !!bool True

# Осуществлять проверку объявлений с теми которые ранее уже собирались
check_new_ad_on_processed: !!bool True

# Задержка между загрузкой страниц в секундах
delay: 
  from: !!int 10
  to: !!int 10

# Использовать прокси при сборе
use_proxy: !!bool True

# Режим работы сбора ссылок и данных с объявлений
# get_ads - собирать ссылки объявлений
# ads_data - собирать информацию из объявлений
# all - Выполнить полный сбор данных. Очередность сбора 1 - сбор ссылок, 2 - сбор информации
work_mode: !!str all