Категории: 
  1:
    name: Купить жильё/Все квартиры
    value: categoryId=24&params[201]=1059
  2:
    name: Купить жильё/Вторичка
    value: categoryId=24&params[201]=1059&params[499][0]=5254
  3:
    name: Купить жильё/Новостройки
    value: categoryId=24&params[201]=1059&params[499][0]=5255
  4:
    name: Купить жильё/Дома, дачи и коттеджи
    value: categoryId=25&params[202]=1064
  5:
    name: Купить жильё/Комнаты
    value: categoryId=23&params[200]=1054
  6:
    name: Снять посуточно/Квартиры
    value: categoryId=24&params[201]=1060&params[504]=5257
  7:
    name: Снять посуточно/Дома, дачи и коттеджи
    value: categoryId=25&params[202]=1065&params[528]=5477
  8:
    name: Снять посуточно/Комнаты и койко-места
    value: categoryId=23&params[200]=1055&params[596]=6204
  9:
    name: Снять долгосрочно/Квартиры
    value: categoryId=24&params[201]=1060&params[504]=5256
  10:
    name: Снять долгосрочно/Дома, дачи и коттеджи
    value: categoryId=25&params[202]=1065&params[528]=5476
  11:
    name: Снять долгосрочно/Комнаты и койко-места
    value: categoryId=23&params[200]=1055&params[596]=6203
  12:
    name: Коммерческая недвижимость/Купить
    value: categoryId=42&params[536]=5545
  13:
    name: Коммерческая недвижимость/Снять
    value: categoryId=42&params[536]=5546
  14:
    name: Другие категории/Земельные участки
    value: categoryId=26
  15:
    name: Другие категории/Гаражи и машиноместа
    value: categoryId=85
  16:
    name: Другие категории/Зарубежная недвижимость
    value: categoryId=86

# Ссылка запроса на получение ID города
# https://www.avito.ru/web/1/slocations?locationId=637640&limit=10&q=(Город для поиска)
Локация:
  1: 
    name: Республика Адыгея
    value: locationId=645530
  2: 
    name: Майкоп
    value: locationId=645660
  3: 
    name: Республика Башкортостан
    value: locationId=645790
  4:
    name: Уфа
    value: locationId=646600
  5:
    name: Республика Бурятия
    value: locationId=623845
  6:
    name: Улан-Удэ
    value: locationId=653271
  7:
    name: Республика Алтай
    value: locationId=662811
  8:
    name: Горно-Алтайск
    value: locationId=662812
  9:
    name: Республика Дагестан
    value: locationId=646710
  10:
    name: Махачкала
    value: locationId=647420
  11:
    name: Республика Ингушетия
    value: locationId=628455
  12:
    name: Магас
    value: locationId=653323
  13:
    name: Республика Кабардино-Балкария
    value: locationId=629430
  14:
    name: Нальчик
    value: locationId=629770
  15:
    name: Республика Калмыкия
    value: locationId=629995
  16:
    name: Элиста
    value: locationId=653341
  17:
    name: Республика Карачаево-Черкесия
    value: locationId=630750
  18:
    name: Черкесск
    value: locationId=631060
  19:
    name: Республика Карелия
    value: locationId=648070
  20:
    name: Петрозаводск
    value: locationId=648220
  21:
    name: Республика Коми
    value: locationId=648340
  22:
    name: Сыктывкар
    value: locationId=648630
  23:
    name: Республика Марий Эл
    value: locationId=648730
  24:
    name: Йошкар-Ола
    value: locationId=648760
  25:
    name: Республика Мордовия
    value: locationId=648960
  26:
    name: Саранск
    value: locationId=649210
  27:
    name: Республика Якутия
    value: locationId=649330
  28:
    name: Якутск
    value: locationId=649810
  29:
    name: Республика Северная Осетия-Алания
    value: locationId=649820
  30:
    name: Владикавказ
    value: locationId=649870
  31:
    name: Республика Татарстан
    value: locationId=650130
  32:
    name: Казань
    value: locationId=650400
  33:
    name: Республика Тыва
    value: locationId=650690
  34:
    name: Кызыл
    value: locationId=650740
  35:
    name: Удмуртская Республика
    value: locationId=659200
  36:
    name: Ижевск
    value: locationId=659300
  37:
    name: Республика Хакасия
    value: locationId=650890
  38:
    name: Абакан
    value: locationId=650910
  39:
    name: Республика Чеченская
    value: locationId=660711
  40:
    name: Грозный
    value: locationId=653391
  41:
    name: Республика Чувашия
    value: locationId=662000
  42:
    name: Чебоксары
    value: locationId=662210
  43:
    name: Алтайский край
    value: locationId=621590
  44:
    name: Барнаул
    value: locationId=621630
  45:
    name: Краснодарский край
    value: locationId=632660
  46:
    name: Краснодар
    value: locationId=633540
  47:
    name: Красноярский край
    value: locationId=634930
  48:
    name: Красноярск
    value: locationId=635320
  49:
    name: Приморский край
    value: locationId=644490
  50:
    name: Владивосток
    value: locationId=644560
  51:
    name: Ставропольский край
    value: locationId=655190
  52:
    name: Ставрополь
    value: locationId=656350
  53:
    name: Хабаровский край
    value: locationId=659930
  54:
    name: Хабаровск
    value: locationId=660250
  55:
    name: Амурская область
    value: locationId=622470
  56:
    name: Благовещенск
    value: locationId=622500
  57:
    name: Архангельская область
    value: locationId=622650
  58:
    name: Архангельск
    value: locationId=622660
  59:
    name: Астраханская область
    value: locationId=623110
  60:
    name: Астрахань
    value: locationId=623130
  61:
    name: Белгородская область
    value: locationId=623410
  62:
    name: Белгород
    value: locationId=623430
  63:
    name: Брянская область
    value: locationId=623840
  64:
    name: Брянск
    value: locationId=623880
  65:
    name: Владимирская область
    value: locationId=624300
  66:
    name: Владимир
    value: locationId=624360
  67:
    name: Волгоградская область
    value: locationId=624770
  68:
    name: Волгоград
    value: locationId=624840
  69:
    name: Вологодская область
    value: locationId=625330
  70:
    name: Вологда
    value: locationId=625330
  71:
    name: Воронежская область
    value: locationId=625670
  72:
    name: Воронеж
    value: locationId=625810
  73:
    name: Ивановская область
    value: locationId=628450
  74:
    name: Иваново
    value: locationId=628500
  75:
    name: Иркутская область
    value: locationId=628780
  76:
    name: Иркутск
    value: locationId=628970
  77:
    name: Калининградская область
    value: locationId=629990
  78:
    name: Калининград
    value: locationId=630090
  79:
    name: Калужская область
    value: locationId=630270
  80:
    name: Калуга
    value: locationId=630410
  81:
    name: Камчатский край
    value: locationId=630660
  82:
    name: Петропавловск-Камчатский
    value: locationId=630730
  83:
    name: Кемеровская область
    value: locationId=631080
  84:
    name: Кемерово
    value: locationId=631270
  85:
    name: Кировская область
    value: locationId=631730
  86:
    name: Киров
    value: locationId=631870
  84:
    name: Костромская область
    value: locationId=632390
  88:
    name: Кострома
    value: locationId=632490
  89: 
    name: Курганская область
    value: locationId=635730
  90: 
    name: Курган
    value: locationId=635860
  91: 
    name: Курская область
    value: locationId=636030
  92:
    name: Курск
    value: locationId=636160
  93:
    name: Ленинградская область
    value: locationId=636370
  94:
    name: Санкт-Петербург
    value: locationId=636370
  95:
    name: Липецкая область
    value: locationId=637260
  96:
    name: Липецк
    value: locationId=637440
  97:
    name: Магаданская область
    value: locationId=637530
  98:
    name: Магадан
    value: locationId=637540
  99:
    name: Московская область
    value: locationId=637680
  100:
    name: Москва
    value: locationId=637640
  101:
    name: Мурманская область
    value: locationId=640000
  102:
    name: Мурманск
    value: locationId=640160
  103:
    name: Нижегородская область
    value: locationId=640310
  104:
    name: Нижний Новгород
    value: locationId=640860
  105:
    name: Новгородская область
    value: locationId=641240
  106:
    name: Великий Новгород
    value: locationId=641270
  107:
    name: Новосибирская область
    value: locationId=641470
  108:
    name: Новосибирск
    value: locationId=641780
  109:
    name: Омская область
    value: locationId=642020
  110:
    name: Омск
    value: locationId=642320
  111:
    name: Оренбургская область
    value: locationId=642480
  112:
    name: Оренбург
    value: locationId=642790
  113:
    name: Орловская область
    value: locationId=643030
  114:
    name: Орел
    value: locationId=643190
  115:
    name: Пензенская область
    value: locationId=643250
  116:
    name: Пенза
    value: locationId=643560
  117:
    name: Пермский край
    value: locationId=643700
  118:
    name: Пермь
    value: locationId=644200
  119:
    name: Псковская область
    value: locationId=645260
  120:
    name: Псков
    value: locationId=645450
  121:
    name: Ростовская область
    value: locationId=651110
  122:
    name: Ростов-на-Дону
    value: locationId=652000
  123:
    name: Рязанская область
    value: locationId=652220
  124:
    name: Рязань
    value: locationId=652430
  125:
    name: Самарская область
    value: locationId=652560
  126:
    name: Самара
    value: locationId=653040
  127:
    name: Саратовская область
    value: locationId=653420
  128:
    name: Саратов
    value: locationId=653241
  129:
    name: Сахалинская область
    value: locationId=653430
  130:
    name: Южно-Сахалинск
    value: locationId=653690
  131:
    name: Свердловская область
    value: locationId=653700
  132:
    name: Екатеринбург
    value: locationId=654070
  133:
    name: Смоленская область
    value: locationId=654860
  134:
    name: Смоленск
    value: locationId=655100
  135:
    name: Тамбовская область
    value: locationId=656520
  136:
    name: Тамбов
    value: locationId=656830
  137:
    name: Тверская область
    value: locationId=656890
  138:
    name: Тверь
    value: locationId=656901
  139:
    name: Томская область
    value: locationId=657310
  140:
    name: Томск
    value: locationId=657600
  141:
    name: Тульская область
    value: locationId=657610
  142:
    name: Тула
    value: locationId=658080
  143:
    name: Тюменская область
    value: locationId=658170
  144:
    name: Тюмень
    value: locationId=659020
  145:
    name: Ульяновская область
    value: locationId=659540
  146:
    name: Ульяновск
    value: locationId=659880
  147:
    name: Челябинская область
    value: locationId=660710
  148:
    name: Челябинск
    value: locationId=661420
  149:
    name: Забайкальский край
    value: locationId=661460
  150:
    name: Чита
    value: locationId=661950
  151:
    name: Ярославская область
    value: locationId=662530
  152:
    name: Ярославль
    value: locationId=662810
  153:
    name: Ненецкий автономный округ
    value: locationId=640001
  154:
    name: Нарьян-Мар
    value: locationId=653371
  155:
    name: Ханты-Мансийский автономный округ - Югра
    value: locationId=660300
  156:
    name: Ханты-Мансийск
    value: locationId=660680
  157:
    name: Чукотский автономный округ
    value: locationId=662280
  158:
    name: Анадырь
    value: locationId=662290
  159:
    name: Ямало-Ненецкий автономный округ
    value: locationId=662330
  160:
    name: Салехард
    value: locationId=662460
  161:
    name: Республика Крым
    value: locationId=621550
  162:
    name: Симферополь
    value: locationId=621565
  163:
    name: Севастополь
    value: locationId=621585
  164:
    name: Санкт-Петербург и ЛО
    value: locationId=107621
  165:
    name: Москва и МО
    value: locationId=107620