Категории: 
  1:
    name: Купить жильё/Все квартиры
    value:  24&params[201]=1059
  2:
    name: Купить жильё/Вторичка
    value:  24&params[201]=1059&params[499][0]=5254
  3:
    name: Купить жильё/Новостройки
    value:  24&params[201]=1059&params[499][0]=5255
  4:
    name: Купить жильё/Дома, дачи и коттеджи
    value:  25&params[202]=1064
  5:
    name: Купить жильё/Комнаты
    value:  23&params[200]=1054
  6:
    name: Снять посуточно/Квартиры
    value:  24&params[201]=1060&params[504]=5257
  7:
    name: Снять посуточно/Дома, дачи и коттеджи
    value:  25&params[202]=1065&params[528]=5477
  8:
    name: Снять посуточно/Комнаты и койко-места
    value:  23&params[200]=1055&params[596]=6204
  9:
    name: Снять долгосрочно/Квартиры
    value:  24&params[201]=1060&params[504]=5256
  10:
    name: Снять долгосрочно/Дома, дачи и коттеджи
    value:  25&params[202]=1065&params[528]=5476
  11:
    name: Снять долгосрочно/Комнаты и койко-места
    value:  23&params[200]=1055&params[596]=6203
  12:
    name: Коммерческая недвижимость/Купить
    value:  42&params[536]=5545
  13:
    name: Коммерческая недвижимость/Снять
    value:  42&params[536]=5546
  14:
    name: Другие категории/Земельные участки
    value:  26
  15:
    name: Другие категории/Гаражи и машиноместа
    value:  85
  16:
    name: Другие категории/Зарубежная недвижимость
    value:  86

# Ссылка запроса на получение ID города
# https://www.avito.ru/web/1/slocations?locationId=637640&limit=10&q=(Город для поиска)
Локация:
  1:
    name: Московская область
    value:  637680
  2:
    name: Москва и МО
    value:  107620
  3:
    name: Москва
    value:  637642
  4:
    name: Наро-Фоминск
    value:  637680
  5:
    name: Балашиха
    value:  637680
  6:
    name: Химки
    value:  639740
  7:
    name: Домодедово
    value:  638150
  8:
    name: Подольск
    value:  639180
  9:
    name: Королев
    value:  638520
  10:
    name: Мытищи
    value:  638920
  11:
    name: Люберцы
    value:  638790
  12:
    name: Электросталь
    value:  637680
  13:
    name: Калужская область
    value:  630270
  14:
    name: Калуга
    value:  630410
  15:
    name: Обнинск
    value:  630530
  16:
    name: Людиново
    value:  630480
  17:
    name: Малоярославец
    value:  630490
  18:
    name: Балабаново
    value:  630290
  19:
    name: Козельск
    value:  630430
  20:
    name: Кондрово
    value:  630440
  21:
    name: Сухиничи
    value:  630590
  22:
    name: Владимирская область
    value:  624300
  23:
    name: Владимир
    value:  624360
  24:
    name: Ковров
    value:  624480
  25:
    name: Муром
    value:  624600
  26:
    name: Александров
    value:  624310
  27:
    name: Гусь-Хрустальный
    value:  624430
  28:
    name: Кольчугино
    value:  624490
  29:
    name: Вязники
    value:  624380
  30:
    name: Киржач
    value:  624470
  31:
    name: Юрьев-Польский
    value:  624760
  32:
    name: Республика Адыгея
    value:  645530
  33:
    name: Майкоп
    value:  645660
  34:
    name: Республика Башкортостан
    value:  645790
  35:
    name: Уфа
    value:  646600
  36:
    name: Республика Бурятия
    value:  623845
  37:
    name: Улан-Удэ
    value:  653271
  39:
    name: Республика Алтай
    value:  662811
  40:
    name: Горно-Алтайск
    value:  662812
  41:
    name: Республика Дагестан
    value:  646710
  42:
    name: Махачкала
    value:  647420
  43:
    name: Республика Ингушетия
    value:  628455
  44:
    name: Магас
    value:  628455
  45:
    name: Республика Кабардино-Балкария
    value:  629430
  46:
    name: Нальчик
    value:  629770
  47:
    name: Республика Калмыкия
    value:  629995
  48:
    name: Элиста
    value:  653341
  49:
    name: Республика Карачаево-Черкесия
    value:  630750
  50:
    name: Черкесск
    value:  631060
  51:
    name: Республика Карелия
    value:  648070
  52:
    name: Петрозаводск
    value:  648220
  53:
    name: Республика Коми
    value:  648340
  54:
    name: Сыктывкар
    value:  648630
  56:
    name: Республика Марий Эл
    value:  648730
  57:
    name: Йошкар-Ола
    value:  648760
  58:
    name: Республика Мордовия
    value:  648960
  59:
    name: Саранск
    value:  649210
  60:
    name: Республика Якутия
    value:  649330
  61:
    name: Якутск
    value:  649810
  62:
    name: Республика Северная Осетия-Алания
    value:  649820
  63:
    name: Владикавказ
    value:  649870
  64:
    name: Республика Татарстан
    value:  650130
  65:
    name: Казань
    value:  650400
  66:
    name: Республика Тыва
    value:  650690
  67:
    name: Кызыл
    value:  650740
  68:
    name: Республика Удмуртская
    value:  659200
  69:
    name: Ижевск
    value:  659300
  70:
    name: Республика Хакасия
    value:  650890
  71:
    name: Абакан
    value:  650910
  72:
    name: Республика Чеченская
    value:  660711
  73:
    name: Грозный
    value:  653391
  74:
    name: Республика Чувашия
    value:  662000
  75:
    name: Чебоксары
    value:  662210
  76:
    name: Алтайский край
    value:  621590
  77:
    name: Барнаул
    value:  621630
  78:
    name: Краснодарский край
    value:  632660
  79:
    name: Краснодар
    value:  633540
  80:
    name: Красноярский край
    value:  634930
  81:
    name: Красноярск
    value:  635320
  82:
    name: Приморский край
    value:  644490
  83:
    name: Владивосток
    value:  644560
  84:
    name: Ставропольский край
    value:  655190
  85:
    name: Ставрополь
    value:  656350
  86:
    name: Хабаровский край
    value:  659930
  87:
    name: Хабаровск
    value:  660250
  88:
    name: Амурская область
    value:  622470
  89:
    name: Благовещенск
    value:  622500
  90:
    name: Архангельская область
    value:  622650
  91:
    name: Архангельск
    value:  622660
  92:
    name: Астраханская область
    value:  623110
  93:
    name: Астрахань
    value:  623130
  94:
    name: Белгородская область
    value:  623410
  95:
    name: Белгород
    value:  623430
  96:
    name: Брянская область
    value:  623840
  97:
    name: Брянск
    value:  623880
  98:
    name: Владимирская область
    value:  624300
  99:
    name: Владимир
    value:  624360
  100:
    name: Волгоградская область
    value:  624770
  101:
    name: Волгоград
    value:  624840
  102:
    name: Вологодская область
    value:  625330
  103:
    name: Вологда
    value:  625390
  104:
    name: Воронежская область
    value:  625670
  105:
    name: Воронеж
    value:  625810
  106:
    name: Ивановская область
    value:  628450
  107:
    name: Иваново
    value:  628500
  108:
    name: Иркутская область
    value:  628780
  109:
    name: Иркутск
    value:  628970
  110:
    name: Калининградская область
    value:  629990
  111:
    name: Калининград
    value:  630090
  112:
    name: Камчатский край
    value:  630660
  113:
    name: Петропавловск-Камчатский
    value:  630730
  114:
    name: Кемеровская область
    value:  631080
  115:
    name: Кемерово
    value:  631270
  116:
    name: Кировская область
    value:  631730
  117:
    name: Киров
    value:  631870
  118:
    name: Костромская область
    value:  632390
  119:
    name: Кострома
    value:  632490
  120:
    name: Курганская область
    value:  635730
  121:
    name: Курган
    value:  635860
  122:
    name: Курская область
    value:  636160
  123:
    name: Курск
    value:  636030
  124:
    name: Ленинградская область
    value:  636370
  125:
    name: Санкт-Петербург
    value:  653240
  126:
    name: Липецкая область
    value:  637260
  127:
    name: Липецк
    value:  637440
  128:
    name: Магаданская область
    value:  637530
  129:
    name: Магадан
    value:  637540
  130:
    name: Мурманская область
    value:  640000
  131:
    name: Мурманск
    value:  640160
  132:
    name: Нижегородская область
    value:  640310
  133:
    name: Нижний Новгород
    value:  640860
  134:
    name: Новгородская область
    value:  641240
  135:
    name: Великий Новгород
    value:  641270
  136:
    name: Новосибирская область
    value:  641470
  137:
    name: Новосибирск
    value:  641780
  138:
    name: Омская область
    value:  642020
  139:
    name: Омск
    value:  642320
  140:
    name: Оренбургская область
    value:  642480
  141:
    name: Оренбург
    value:  642790
  142:
    name: Орловская область
    value:  643030
  143:
    name: Орел
    value:  643190
  144:
    name: Пензенская область
    value:  643250
  145:
    name: Пенза
    value:  643560
  146:
    name: Пермский край
    value:  643700
  147:
    name: Пермь
    value:  644200
  148:
    name: Псковская область
    value:  645260
  149:
    name: Псков
    value:  645450
  150:
    name: Ростовская область
    value:  651110
  151:
    name: Ростов-на-Дону
    value:  652000
  152:
    name: Рязанская область
    value:  652220
  153:
    name: Рязань
    value:  652430
  154:
    name: Самарская область
    value:  652560
  155:
    name: Самара
    value:  653040
  156:
    name: Саратовская область
    value:  653420
  157:
    name: Саратов
    value:  653241
  158:
    name: Сахалинская область
    value:  653430
  159:
    name: Южно-Сахалинск
    value:  653690
  160:
    name: Свердловская область
    value:  653700
  161:
    name: Екатеринбург
    value:  654070
  162:
    name: Смоленская область
    value:  654860
  163:
    name: Смоленск
    value:  655100
  164:
    name: Тамбовская область
    value:  656520
  165:
    name: Тамбов
    value:  656830
  166:
    name: Тверская область
    value:  656890
  167:
    name: Тверь
    value:  656901
  168:
    name: Томская область
    value:  657310
  169:
    name: Томск
    value:  657600
  170:
    name: Тульская область
    value:  657610
  171:
    name: Тула
    value:  658080
  172:
    name: Тюменская область
    value:  658170
  173:
    name: Тюмень
    value:  659020
  174:
    name: Ульяновская область
    value:  659540
  175:
    name: Ульяновск
    value:  659880
  176:
    name: Челябинская область
    value:  660710
  177:
    name: Челябинск
    value:  661420
  178:
    name: Забайкальский край
    value:  661460
  179:
    name: Чита
    value:  661950
  180:
    name: Ярославская область
    value:  662530
  181:
    name: Ярославль
    value:  662810
  182:
    name: Ненецкий автономный округ
    value:  640001
  183:
    name: Нарьян-Мар
    value:  653371
  184:
    name: Ханты-Мансийский автономный округ - Югра
    value:  660300
  185:
    name: Ханты-Мансийск
    value:  660680
  186:
    name: Чукотский автономный округ
    value:  662280
  187:
    name: Анадырь
    value:  662290
  188:
    name: Ямало-Ненецкий автономный округ
    value:  662330
  189:
    name: Салехард
    value:  662460
  190:
    name: Республика Крым
    value:  621550
  191:
    name: Симферополь
    value:  621565
  192:
    name: Севастополь
    value:  621585
  193:
    name: Санкт-Петербург и ЛО
    value:  107621