Категории: 
  1:
    name: Купить жильё/Все квартиры
    value: categoryId=24&params[201]=1059
  2:
    name: Купить жильё/Вторичка
    value: categoryId=24&params[201]=1059&params[499][0]=5254
  3:
    name: Купить жильё/Новостройки
    value: categoryId=24&params[201]=1059&params[499][0]=5255
  4:
    name: Купить жильё/Дома, дачи и коттеджи
    value: categoryId=25&params[202]=1064
  5:
    name: Купить жильё/Комнаты
    value: categoryId=23&params[200]=1054
  6:
    name: Снять посуточно/Квартиры
    value: categoryId=24&params[201]=1060&params[504]=5257
  7:
    name: Снять посуточно/Дома, дачи и коттеджи
    value: categoryId=25&params[202]=1065&params[528]=5477
  8:
    name: Снять посуточно/Комнаты и койко-места
    value: categoryId=23&params[200]=1055&params[596]=6204
  9:
    name: Снять долгосрочно/Квартиры
    value: categoryId=24&params[201]=1060&params[504]=5256
  10:
    name: Снять долгосрочно/Дома, дачи и коттеджи
    value: categoryId=25&params[202]=1065&params[528]=5476
  11:
    name: Снять долгосрочно/Комнаты и койко-места
    value: categoryId=23&params[200]=1055&params[596]=6203
  12:
    name: Коммерческая недвижимость/Купить
    value: categoryId=42&params[536]=5545
  13:
    name: Коммерческая недвижимость/Снять
    value: categoryId=42&params[536]=5546
  14:
    name: Другие категории/Земельные участки
    value: categoryId=26
  15:
    name: Другие категории/Гаражи и машиноместа
    value: categoryId=85
  16:
    name: Другие категории/Зарубежная недвижимость
    value: categoryId=86

# Ссылка запроса на получение ID города
# https://www.avito.ru/web/1/slocations?locationId=637640&limit=10&q=(Город для поиска)
Локация:
  1: 
    name: Московская область
    value: locationId=637680
  2: 
    name: Москва
    value: locationId=637640
  3: 
    name: Москва и МО
    value: locationId=107620
  4:
    name: Калужская область
    value: locationId=630270
  5:
    name: Калуга
    value: locationId=630410
  6:
    name: Обнинск
    value: locationId=630530