Категории: 
  1:
    name: Купить жильё/Все квартиры
    value: categoryId=24&params[201]=1059
  2:
    name: Купить жильё/Вторичка
    value: categoryId=24&params[201]=1059&params[499][0]=5254
  3:
    name: Купить жильё/Новостройки
    value: categoryId=24&params[201]=1059&params[499][0]=5255
  4:
    name: Купить жильё/Дома, дачи и коттеджи
    value: categoryId=25&params[202]=1064
  5:
    name: Купить жильё/Комнаты
    value: categoryId=23&params[200]=1054
  6:
    name: Снять посуточно/Квартиры
    value: categoryId=24&params[201]=1060&params[504]=5257
  7:
    name: Снять посуточно/Дома, дачи и коттеджи
    value: categoryId=25&params[202]=1065&params[528]=5477
  8:
    name: Снять посуточно/Комнаты и койко-места
    value: categoryId=23&params[200]=1055&params[596]=6204
  9:
    name: Снять долгосрочно/Квартиры
    value: categoryId=24&params[201]=1060&params[504]=5256
  10:
    name: Снять долгосрочно/Дома, дачи и коттеджи
    value: categoryId=25&params[202]=1065&params[528]=5476
  11:
    name: Снять долгосрочно/Комнаты и койко-места
    value: categoryId=23&params[200]=1055&params[596]=6203
  12:
    name: Коммерческая недвижимость/Купить
    value: categoryId=42&params[536]=5545
  13:
    name: Коммерческая недвижимость/Снять
    value: categoryId=42&params[536]=5546
  14:
    name: Другие категории/Земельные участки
    value: categoryId=26
  15:
    name: Другие категории/Гаражи и машиноместа
    value: categoryId=85
  16:
    name: Другие категории/Зарубежная недвижимость
    value: categoryId=86

# Ссылка запроса на получение ID города
# https://www.avito.ru/web/1/slocations?locationId=637640&limit=10&q=(Город для поиска)
Локация:
  1: 
    name: Республика Адыгея
    value: 
  2: 
    name: Майкоп
    value: 
  3: 
    name: 	Республика Башкортостан
    value: 
  4:
    name: Уфа
    value: 
  5:
    name: Республика Бурятия
    value: 
  6:
    name: Улан-Удэ
    value: 
  7:
    name: Республика Алтай
    value: 
  8:
    name: Горно-Алтайск
    value:
  9:
    name: Республика Дагестан
    value:
  10:
    name: Махачкала
    value:
  11:
    name: Республика Ингушетия
    value:
  12:
    name: Магас
    value:
  13:
    name: Кабардино-Балкарская Республика
    value:
  14:
    name: Нальчик
    value:
  15:
    name: Республика Калмыкия
    value:
  16:
    name: Элиста
    value:
  17:
    name: 
    value:
  18:
    name: 
    value:
  19:
    name: 
    value:
  20:
    name: 
    value:
  21:
    name: 
    value:
  22:
    name: 
    value:
  23:
    name: 
    value:
  24:
    name: 
    value:
  25:
    name: 
    value:
  26:
    name: 
    value:
  27:
    name: 
    value:
  28:
    name: 
    value:
  29:
    name: 
    value:
  30:
    name: 
    value:
  31:
    name: 
    value:
  32:
    name: 
    value:
  33:
    name: 
    value:
  34:
    name: 
    value:
  35:
    name: 
    value:
  36:
    name: 
    value:
  37:
    name: 
    value:
  38:
    name: 
    value:
  39:
    name: 
    value:
  40:
    name: 
    value:
  41:
    name: 
    value:
  42:
    name: 
    value:
  43:
    name: 
    value:
  44:
    name: 
    value:
  45:
    name: 
    value:
  46:
    name: 
    value:
  47:
    name: 
    value:
  48:
    name: 
    value:
  49:
    name: 
    value:
  50:
    name: 
    value:
  51:
    name: 
    value:
  52:
    name: 
    value:
  53:
    name: 
    value:
  54:
    name: 
    value:
  55:
    name: 
    value:
  56:
    name: 
    value:
  57:
    name: 
    value:
  58:
    name: 
    value:
  59:
    name: 
    value:
  60:
    name: 
    value:
  61:
    name: 
    value:
  62:
    name: 
    value:
  63:
    name: 
    value:
  64:
    name: 
    value:
  65:
    name: 
    value:
  66:
    name: 
    value:
  67:
    name: 
    value:
  68:
    name: 
    value:
  69:
    name: 
    value:
  70:
    name: 
    value:
  71:
    name: 
    value:
  72:
    name: 
    value:
  73:
    name: 
    value:
  74:
    name: 
    value:
  75:
    name: 
    value:
  76:
    name: 
    value:
  77:
    name: 
    value:
  78:
    name: 
    value:
  79:
    name: 
    value:
  80:
    name: 
    value:
  81:
    name: 
    value:
  82:
    name: 
    value:
  83:
    name: 
    value:
  84:
    name: 
    value:
  85:
    name: 
    value:
  86:
    name: 
    value:
  84:
    name: 
    value:
  88:
    name: 
    value: