Категории: 
  Купить жильё:
    Все квартиры:
      categoryId: 24&params[201]=1059
    Вторичка:
      categoryId: 24&params[201]=1059&params[499][0]=5254
    Новостройки:
      categoryId: 24&params[201]=1059&params[499][0]=5255
    Дома, дачи и коттеджи: 
      categoryId: 25&params[202]=1064
    Комнаты: 
      categoryId: 23&params[200]=1054
  Снять посуточно:
    Квартиры: 
        categoryId: 24&params[201]=1060&params[504]=5257
    Дома, дачи и коттеджи: 
        categoryId: 25&params[202]=1065&params[528]=5477
    Комнаты и койко-места: 
        categoryId: 23&params[200]=1055&params[596]=6204
  Снять долгосрочно:
    Квартиры: 
        categoryId: 24&params[201]=1060&params[504]=5256
    Дома, дачи и коттеджи: 
        categoryId: 25&params[202]=1065&params[528]=5476
    Комнаты и койко-места: 
        categoryId: 23&params[200]=1055&params[596]=6203
  Коммерческая недвижимость:
    Купить:
      categoryId: 42&params[536]=5545
    Снять:
      categoryId: 42&params[536]=5546
  Другие категории:
    Земельные участки: 
      categoryId: 26
    Гаражи и машиноместа: 
      categoryId: 85
    Зарубежная недвижимость: 
      categoryId: 86

# Ссылка запроса на получение ID города
# https://www.avito.ru/web/1/slocations?locationId=637640&limit=10&q=(Город для поиска)
Локация:
  Московская область: 637680
  Москва: 637640
  Москва и МО: 107620
  Калужская область: 630270
  Калуга: 630410
  Обнинск: 630530